DECLARE
 Prole VARCHAR2(64);
 RESULTS VARCHAR2(8);
BEGIN
 Prole:=APEX_UTIL.GET_SESSION_STATE('user_role');
 IF Prole = 'DOCTOR' THEN
  RESULTS:='2';
 ELSIF Prole = 'PATIENT' THEN 
  RESULTS:='4';
 ELSIF Prole = 'RECEPTIONIST' THEN 
  RESULTS:='41';
 END IF;
 RETURN RESULTS;
END;