SELECT
    A.APPOINTMENT_ID,
    A.APPOINTMENT_DATE,
    A.APPOINTMENT_DURATION,
    P.PATIENT_ID,
    P.FULL_NAME AS PATIENT_NAME,
    P.CONTACT_NUMBER AS PATIENT_PHONE,
    A.STATUS,
    A.REASON
FROM
    APPOINTMENTS A
JOIN
    PATIENTS P ON A.PATIENT_ID = P.PATIENT_ID
JOIN
    DOCTORS D ON A.DOCTOR_ID = D.DOCTOR_ID
WHERE
    TRIM(UPPER(D.DOCTOR_ID)) = TRIM(UPPER(:APP_USER)) 
    AND (
    TO_CHAR(A.APPOINTMENT_DATE, 'YYYY-MM-DD') = TO_CHAR(SYSDATE, 'YYYY-MM-DD') 
    OR
    TO_CHAR(A.APPOINTMENT_DATE) BETWEEN SYSDATE AND (SYSDATE + 6 )
    )
    ORDER BY APPOINTMENT_DATE;